// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq8MbSiwFyzq5aw4V1i2p2dkTjWEf_Z6s',
    appId: '1:444118543116:web:97b5e5fb931164e2c9b729',
    messagingSenderId: '444118543116',
    projectId: 'sharebite-fixed',
    authDomain: 'sharebite-fixed.firebaseapp.com',
    storageBucket: 'sharebite-fixed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwWD66D6nRV4eJ4k0FgbMx79WWUxH_3lk',
    appId: '1:444118543116:android:a30bb4e2879cf6b9c9b729',
    messagingSenderId: '444118543116',
    projectId: 'sharebite-fixed',
    storageBucket: 'sharebite-fixed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiwrGNLKSH8keZxg8IYS9F18q91oCC124',
    appId: '1:444118543116:ios:89e62101d9df8725c9b729',
    messagingSenderId: '444118543116',
    projectId: 'sharebite-fixed',
    storageBucket: 'sharebite-fixed.firebasestorage.app',
    iosBundleId: 'com.example.sharebiteFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiwrGNLKSH8keZxg8IYS9F18q91oCC124',
    appId: '1:444118543116:ios:89e62101d9df8725c9b729',
    messagingSenderId: '444118543116',
    projectId: 'sharebite-fixed',
    storageBucket: 'sharebite-fixed.firebasestorage.app',
    iosBundleId: 'com.example.sharebiteFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq8MbSiwFyzq5aw4V1i2p2dkTjWEf_Z6s',
    appId: '1:444118543116:web:7bec8992e45932d8c9b729',
    messagingSenderId: '444118543116',
    projectId: 'sharebite-fixed',
    authDomain: 'sharebite-fixed.firebaseapp.com',
    storageBucket: 'sharebite-fixed.firebasestorage.app',
  );

}